"use client";

import { useAuth } from "@clerk/nextjs";
import { BadgeCheck, Building2, FileSpreadsheet, Link2, Plus, Scale, ShieldCheck } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

import type { BankingWorkspace } from "../../lib/api";
import { Button, StatusBadge } from "../_components/design-system";
import { labelize } from "../os-utils";
import styles from "./banking-workspace.module.css";

type Preview = { total_rows: number; valid_rows: number; invalid_rows: number; duplicate_rows: number; can_import: boolean; rows: Array<{ row_number: number; status: string; occurred_on: string | null; description: string | null; amount_cents: number | null; validation_errors: string[] }> };

function money(cents: number) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(cents / 100); }
function cents(value: string) { const number = Number(value.replace(/[$,]/g, "")); return Number.isFinite(number) ? Math.round(number * 100) : 0; }
function tone(status: string): "neutral" | "info" | "success" | "warning" | "danger" { if (["approved", "matched", "reconciled", "complete", "active"].includes(status)) return "success"; if (["unmatched", "review"].includes(status)) return "warning"; if (["draft"].includes(status)) return "info"; return "neutral"; }

export function BankingWorkspacePanel({ workspace, canManage }: { workspace: BankingWorkspace; canManage: boolean }) {
  const router = useRouter();
  const { getToken } = useAuth();
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [preview, setPreview] = useState<Preview | null>(null);
  const [pendingImport, setPendingImport] = useState<Record<string, unknown> | null>(null);
  const [accountId, setAccountId] = useState(workspace.accounts[0]?.id ?? "");
  const [journalSelections, setJournalSelections] = useState<Record<string, string>>({});
  const apiBase = useMemo(() => process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000", []);
  const devEmail = useMemo(() => process.env.NEXT_PUBLIC_DEV_USER_EMAIL ?? "richardaustindugger@users.noreply.github.com", []);

  async function request(path: string, body: Record<string, unknown>) {
    const token = await getToken().catch(() => null);
    const headers: Record<string, string> = { "Content-Type": "application/json" };
    if (token) headers.Authorization = `Bearer ${token}`; else headers["X-Dev-User-Email"] = devEmail;
    const response = await fetch(`${apiBase}${path}`, { method: "POST", headers, body: JSON.stringify(body) });
    if (!response.ok) { const data = await response.json().catch(() => null) as { detail?: string } | null; throw new Error(data?.detail ?? "Banking request failed."); }
    return response.json().catch(() => null);
  }
  async function action(work: () => Promise<void>, success: string) { setBusy(true); setMessage(""); try { await work(); setMessage(success); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Banking request failed."); } finally { setBusy(false); } }
  async function createAccount(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); await action(async () => { await request("/api/v1/finance/banking/accounts", { name: String(data.get("name")), institution_name: String(data.get("institution_name")) || null, account_type: String(data.get("account_type")), last_four: String(data.get("last_four")) || null, notes: String(data.get("notes")) || null }); form.reset(); }, "Bank or card account added. No credentials were stored."); }
  async function previewImport(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const file = data.get("file"); if (!(file instanceof File)) return; const payload = { bank_account_id: String(data.get("bank_account_id")), file_name: file.name, csv_content: await file.text(), field_mapping: { date: String(data.get("date_column")), description: String(data.get("description_column")), amount: String(data.get("amount_column")), balance: String(data.get("balance_column")) || undefined, external_id: String(data.get("external_id_column")) || undefined }, opening_balance_cents: data.get("opening_balance") ? cents(String(data.get("opening_balance"))) : null, closing_balance_cents: data.get("closing_balance") ? cents(String(data.get("closing_balance"))) : null };
    Object.entries(payload.field_mapping).forEach(([key, value]) => { if (!value) delete payload.field_mapping[key as keyof typeof payload.field_mapping]; });
    try { setBusy(true); const result = await request("/api/v1/finance/banking/imports/preview", payload); setPreview(result as Preview); setPendingImport(payload); setMessage("Statement preview is ready. Review rows before committing."); } catch (error) { setMessage(error instanceof Error ? error.message : "Statement preview failed."); } finally { setBusy(false); } }
  async function commitImport() { if (!pendingImport) return; await action(async () => { await request("/api/v1/finance/banking/imports", pendingImport); setPreview(null); setPendingImport(null); }, "Statement imported as private evidence. Transactions are ready to match."); }
  async function matchTransaction(id: string) { const journalId = journalSelections[id]; if (!journalId) { setMessage("Select the matching posted journal first."); return; } await action(() => request(`/api/v1/finance/banking/transactions/${id}/match`, { journal_entry_id: journalId, notes: null }), "Bank transaction matched to the posted journal."); }
  async function ignoreTransaction(id: string) { await action(() => request(`/api/v1/finance/banking/transactions/${id}/status`, { status: "ignored", notes: "Not a Stonegate operating transaction." }), "Transaction marked ignored with an audit record."); }
  async function createReconciliation(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await action(() => request("/api/v1/finance/banking/reconciliations", { bank_account_id: String(data.get("bank_account_id")), statement_import_id: String(data.get("statement_import_id")) || null, statement_start_on: String(data.get("statement_start_on")), statement_end_on: String(data.get("statement_end_on")), opening_balance_cents: cents(String(data.get("opening_balance"))), closing_balance_cents: cents(String(data.get("closing_balance"))), notes: String(data.get("notes")) || null }), "Reconciliation prepared. It can be approved only when balanced and fully resolved."); }

  return <section className={styles.workspace}>
    <header><div><span>F6D2 banking control</span><h2>Statement import and reconciliation</h2></div><StatusBadge tone={workspace.summary.unmatched_transactions ? "warning" : "success"}>{workspace.summary.unmatched_transactions ? `${workspace.summary.unmatched_transactions} to match` : "Statements controlled"}</StatusBadge></header>
    <div className={styles.metrics}><div><Building2 size={17}/><span>Active accounts</span><strong>{workspace.summary.active_accounts}</strong></div><div><Link2 size={17}/><span>Unmatched lines</span><strong>{workspace.summary.unmatched_transactions}</strong></div><div><FileSpreadsheet size={17}/><span>Statement imports</span><strong>{workspace.summary.unreconciled_imports}</strong></div><div><Scale size={17}/><span>Open reconciliations</span><strong>{workspace.summary.open_reconciliations}</strong></div></div>
    <section><div className={styles.heading}><div><span>Statement accounts</span><h3>Bank and credit-card records</h3></div><strong>{workspace.accounts.length}</strong></div><div className={styles.accounts}>{workspace.accounts.map(item => <article key={item.id}><div><strong>{item.name}</strong><StatusBadge tone={tone(item.status)}>{labelize(item.account_type)}</StatusBadge></div><span>{item.institution_name ?? "Institution not recorded"}{item.last_four ? ` · •••• ${item.last_four}` : ""}</span><small>{item.unmatched_transaction_count} unmatched transactions</small></article>)}{!workspace.accounts.length ? <p>No accounts are recorded yet.</p> : null}</div></section>
    {canManage ? <div className={styles.forms}><details><summary><Plus size={15}/> Add bank or card account</summary><form onSubmit={createAccount}><label>Name<input name="name" placeholder="Operating checking" required/></label><label>Institution<input name="institution_name" placeholder="Bank name"/></label><label>Type<select name="account_type"><option value="checking">Checking</option><option value="savings">Savings</option><option value="credit_card">Credit card</option><option value="other">Other</option></select></label><label>Last four<input inputMode="numeric" maxLength={4} name="last_four" pattern="\d{4}"/></label><label className={styles.full}>Notes<textarea name="notes" rows={2}/></label><Button disabled={busy} icon={<Plus size={14}/>}>Add account</Button></form></details>
      {workspace.accounts.length ? <details><summary><FileSpreadsheet size={15}/> Preview CSV statement</summary><form onSubmit={previewImport}><label>Account<select name="bank_account_id" value={accountId} onChange={event => setAccountId(event.target.value)}>{workspace.accounts.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>CSV file<input accept=".csv,text/csv" name="file" required type="file"/></label><label>Date column<input defaultValue="Date" name="date_column" required/></label><label>Description column<input defaultValue="Description" name="description_column" required/></label><label>Signed amount column<input defaultValue="Amount" name="amount_column" required/></label><label>Balance column<input defaultValue="Balance" name="balance_column"/></label><label>Transaction ID column<input name="external_id_column"/></label><label>Opening balance<input inputMode="decimal" name="opening_balance" placeholder="Optional"/></label><label>Closing balance<input inputMode="decimal" name="closing_balance" placeholder="Optional"/></label><Button disabled={busy} icon={<FileSpreadsheet size={14}/>}>Preview statement</Button></form>{preview ? <div className={styles.preview}><strong>{preview.valid_rows} valid · {preview.duplicate_rows} duplicates · {preview.invalid_rows} invalid</strong>{preview.rows.slice(0, 8).map(row => <div key={row.row_number}><span>{row.row_number}</span><span>{row.occurred_on ?? "Invalid date"}</span><span>{row.description ?? "Missing description"}</span><b>{row.amount_cents === null ? "" : money(row.amount_cents)}</b><StatusBadge tone={tone(row.status)}>{labelize(row.status)}</StatusBadge></div>)}<Button disabled={busy || !preview.can_import} icon={<ShieldCheck size={14}/>} onClick={() => void commitImport()} type="button">Import reviewed statement</Button></div> : null}</details> : null}</div> : null}
    <section><div className={styles.heading}><div><span>Bank line matching</span><h3>Match cleared cash to posted journals</h3></div><strong>{workspace.transactions.length}</strong></div><div className={styles.table}><table><thead><tr><th>Date</th><th>Description</th><th>Amount</th><th>Status</th><th>Journal</th><th>Action</th></tr></thead><tbody>{workspace.transactions.length ? workspace.transactions.map(item => <tr key={item.id}><td>{item.occurred_on}</td><td>{item.description}</td><td className={item.amount_cents < 0 ? styles.outflow : styles.inflow}>{money(item.amount_cents)}</td><td><StatusBadge tone={tone(item.status)}>{labelize(item.status)}</StatusBadge></td><td>{item.journal_entry_number ?? (canManage && item.status === "unmatched" ? <select aria-label={`Posted journal for ${item.description}`} value={journalSelections[item.id] ?? ""} onChange={event => setJournalSelections(current => ({ ...current, [item.id]: event.target.value }))}><option value="">Select posted journal</option>{workspace.posted_journals.filter(journal => journal.cash_delta_cents === item.amount_cents).map(journal => <option key={journal.id} value={journal.id}>{journal.entry_number} · {journal.memo}</option>)}</select> : "Not matched")}</td><td>{canManage && item.status === "unmatched" ? <><Button disabled={busy} onClick={() => void matchTransaction(item.id)} size="small" type="button" variant="secondary">Match journal</Button><Button disabled={busy} onClick={() => void ignoreTransaction(item.id)} size="small" type="button" variant="quiet">Ignore</Button></> : null}</td></tr>) : <tr><td colSpan={6}>Import a reviewed CSV statement to start matching.</td></tr>}</tbody></table></div></section>
    {canManage && workspace.accounts.length ? <details className={styles.reconcile}><summary><Scale size={15}/> Prepare reconciliation</summary><form onSubmit={createReconciliation}><label>Account<select name="bank_account_id" required>{workspace.accounts.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Statement import<select name="statement_import_id"><option value="">Use date range</option>{workspace.imports.map(item => <option key={item.id} value={item.id}>{item.file_name}</option>)}</select></label><label>Start date<input name="statement_start_on" required type="date"/></label><label>End date<input name="statement_end_on" required type="date"/></label><label>Opening balance<input inputMode="decimal" name="opening_balance" required/></label><label>Closing balance<input inputMode="decimal" name="closing_balance" required/></label><label className={styles.full}>Notes<textarea name="notes" rows={2}/></label><Button disabled={busy} icon={<Scale size={14}/>}>Prepare reconciliation</Button></form></details> : null}
    <section><div className={styles.heading}><div><span>Reconciliation history</span><h3>Statement balance control</h3></div></div><div className={styles.reconciliations}>{workspace.reconciliations.map(item => <div key={item.id}><div><strong>{item.statement_start_on} to {item.statement_end_on}</strong><span>{item.matched_transaction_count} matched · {item.unresolved_transaction_count} unresolved</span></div><b>{item.difference_cents === 0 ? "Balanced" : `${money(item.difference_cents)} difference`}</b><StatusBadge tone={tone(item.status)}>{labelize(item.status)}</StatusBadge>{canManage && item.status === "review" ? <Button disabled={busy} icon={<BadgeCheck size={14}/>} onClick={() => void action(() => request(`/api/v1/finance/banking/reconciliations/${item.id}/approve`, {}), "Balanced reconciliation approved.")} size="small" type="button">Approve</Button> : null}</div>)}{!workspace.reconciliations.length ? <p>No reconciliations prepared.</p> : null}</div></section><p className={styles.message} aria-live="polite">{message}</p>
  </section>;
}
